default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[:database][:username] %>
  password: <%= Rails.application.credentials[:database][:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: bank_account_management_development

test:
  <<: *default
  database: bank_account_management_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %> 
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["BANK_ACCOUNT_MANAGEMENT_DATABASE_PASSWORD"] %>
